---
- hosts: all
  remote_user: root
  sudo: yes
  tasks:
  - name: To install maria DB
    yum: name=mariadb state=latest
    tags: DB
  - name: to install apache
    yum: name=httpd state=latest
    notify: httpd
    tags: apache
  - name: To install elinks
    yum: name=elinks state=latest
    tags: elinks
