---
- name: To copy new files.
  hosts: all
  remote_user: ansible
  become: true
  tasks:
  - name: To install the httpd package on the servers
    yum: name=httpd state=latest
    
  - name: to configure homepage of my Web server
    copy:
      src: index.html
      dest: /var/www/html/
      mode: 0644
    
  - name: To start the service.
    service: name=httpd state=restarted enabled=true

